import Coh.V2.Category

/-!
## Coh V2 Section 9 Worked Example: Discrete Trace

This module implements the worked example from the manuscript, verifying that
evaluating the endpoints of a trace securely bounds the global behavior.
-/

namespace Coh.V2.Example

/-- State space as defined in the example. -/
inductive State
  | x0 | x1 | x2

open State

/-- Violation functional V where V(x0) = 10. -/
def V : State → ℚ
  | x0 => 10
  | x1 => 9  -- Derived bound in example
  | x2 => 7  -- Derived bound in example

/--
A mock system for the example.
In a real case, this would be an instance of a VerifiedSystem.
-/
axiom S : System
axiom A : Assumptions S

/-- Mock trace symbols. -/
axiom r1 : S.Obs.V
axiom r2 : S.Obs.V
axiom r21 : S.Obs.V
axiom h_comp : S.Obs.comp r2 r1 = some r21

/-- Delta bounds assumed in the example. -/
axiom h_delta1 : delta S r1 ≤ 1
axiom h_delta2 : delta S r2 ≤ 1
axiom h_delta21 : delta S r21 ≤ 2

/--
The first transition r1: x0 -> x1
s1 = 2, d1 = 1.
Law: V(x1) + 2 ≤ V(x0) + 1  => 9 + 2 ≤ 10 + 1 (11 ≤ 11)
-/
def mor1 : CertifiedMor S A V x0 x1 where
  trace := r1
  spend := 2
  defect := 1
  spend_nonneg := by linarith
  defect_nonneg := by linarith
  law := by simp [V]; linarith
  defect_bound := h_delta1

/--
The second transition r2: x1 -> x2
s2 = 3, d2 = 1.
Law: V(x2) + 3 ≤ V(x1) + 1  => 7 + 3 ≤ 9 + 1 (10 ≤ 10)
-/
def mor2 : CertifiedMor S A V x1 x2 where
  trace := r2
  spend := 3
  defect := 1
  spend_nonneg := by linarith
  defect_nonneg := by linarith
  law := by simp [V]; linarith
  defect_bound := h_delta2

/--
The global composite transition r21: x0 -> x2.
Generated by syntactic composition in the Coh Category.
-/
def mor21 : CertifiedMor S A V x0 x2 :=
  compose V mor1 mor2 h_comp

/--
Verification of the global boundary (Theorem 6.1).
V(x2) + (s1 + s2) ≤ V(x0) + (d1 + d2)
-/
theorem global_check :
    V x2 + (mor1.spend + mor2.spend) ≤ V x0 + (mor1.defect + mor2.defect) := by
  -- This follows directly from the 'law' of the composite morphism.
  exact mor21.law

/--
Manual evaluation of the example values:
7 + (2 + 3) ≤ 10 + (1 + 1) => 12 ≤ 12.
-/
example : 7 + (2 + 3) ≤ 10 + (1 + 1) := by linarith

end Coh.V2.Example
